### ISSUE TITLE
Error of making plots an safe results by using simple_hot_water_storage

### ISSUE THREAD

**Issue by H0ooo** [FZJ-IEK3-VSA/HiSim#174]
I simulate a system with heatpump, simple hot water storage and heat distribution sytem.
The simulation itself ends fine. But in the post processing while making plots an saving in folders, there will be always an error in some functions:

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/cbf7f1b4-b83b-46e0-af25-abc41404a34b)

**Comment by k-rieck** [comment]
Hello, thanks for your comment. Can you say which example you ran and which simulation parameters you chose in your exmaple? We will have a look.

**Comment by H0ooo** [comment]
Hi I reproduced it using the hisim example "basic_household_with_new_hp_hds_hws_and_pv.py" . I set the simulation parameters to "one_day_only_with_all_options" instead of "full_year" so that the example does not simulate for so long and the error still occurs when creating plots. Attached is a screenshot of the parameters that I have adjusted. Otherwise I have not changed anything in the example.

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/f1eb7d2c-f6e7-4276-9c13-eada004e2836)

Thanks for your support!

**Comment by k-rieck** [comment]
Hey, 
I just pushed a recent version of this example in the branch "kr-fix-basic_household_with_new_hp_hds_hws_and_pv" and normally it should work now. Maybe before you can pull the main HiSim branch again because we made some changes lately. It is a rather old example that we do not use that often anymore, that is why we did not come across this error. Thanks for noticing and commenting! Let us know if you have any more issues :)

**Comment by H0ooo** [comment]
Hi, thanks for working on it.
I update my whole HiSim but still have this error while running the example. Do i have to update some specific files for post processing?

**Comment by H0ooo** [comment]
In addition: I tried to run the example "household_with_advanced_hp_hws_hds_pv.py" and get the same error there. 

![grafik](https://github.com/FZJ-IEK3-VSA/HiSim/assets/139124982/c3c1d0f5-3a06-4979-9197-0c11ce82e181)

**Comment by k-rieck** [comment]
Hey, that is misterious. That error has not appeared so far. I am sorry that I do not have a good answer for you.
Have you checked if your file name is too long?
